baseUrl: http://localhost:80
env:
  username: 'admin'
  password: 'Thinkbig1'
  language: 'zh'
# nfs
  nfsIp: "172.20.151.105"
  nfsPath: "/tmp/nfs/data/e2e-test"
# Keycloak
  oauth2Username: test
  oauth2Password: '123456'
# 集群
  externalIP: 142.22.2.2
  upgradeVersion: v1.23.9
# 节点
  nodeUsername: 'root'
  nodePassword: 'Thinkbig1'
  nodePort: 22
# 镜像仓库
  offLineRegistry: 172.20.139.239:5000
  httpsRegistry: 172.16.29.140
# 备份
  backupS3EndPoint: 172.20.163.233:9000
  backupS3Admin: admin
  backupS3Password: Aa123456
